import { Clef } from '@/types/noteTypes';

const CLEFS: Clef[] = [Clef.Soprano, Clef.Treble, Clef.Bass, Clef.Alto];
enum AllNoteNames {
  DFlat = 'DB',
  EFlat = 'EB',
  GFlat = 'GB',
  AFlat = 'AB',
  BFlat = 'BB',
  C = 'C',
  CSharp = 'C#',
  D = 'D',
  DSharp = 'D#',
  E = 'E',
  F = 'F',
  FSharp = 'F#',
  G = 'G',
  GSharp = 'G#',
  A = 'A',
  ASharp = 'A#',
  B = 'B',
  dFlat = 'db',
  eFlat = 'eb',
  gFlat = 'gb',
  aFlat = 'ab',
  bFlat = 'bb',
  cSharp = 'c#',
  dSharp = 'd#',
  e = 'e',
  f = 'f',
  fSharp = 'f#',
  g = 'g',
  gSharp = 'g#',
  aSharp = 'a#',
  c = 'c',
  a = 'a',
  b = 'b',
  d = 'd',
}

export { AllNoteNames, CLEFS };
